import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppBar from "@/components/AppBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "YouApp Coding Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`wrapper min-h-[100vh] ${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
